### ISSUE TITLE
ubuntu-cloudimg-query outdated, only covering a single cloud and using deprecated querydata

### ISSUE THREAD

**Issue by toabctl** [canonical/cloud-utils#49]
The shipped `ubuntu-cloudimg-query` is outdated (not containing the latest suites, incomplete instance-types list), does only cover a single cloud (AWS) and still uses [deprecated querydata](https://discourse.ubuntu.com/t/impish-indri-release-notes/21951).

Eg. showing the latest image in `eu-central-1` :
```
$ EC2_REGION=eu-central-1 ubuntu-cloudimg-query            
ami-0e2821e7e40783fd1
```

which points to a EOL xenial image:
```
$ aws ec2 describe-images --image-ids ami-0e2821e7e40783fd1|jq '.Images[].ImageLocation'
"amazon/ubuntu/images/ebs-ssd/ubuntu-xenial-16.04-amd64-server-20210928"
```

I propose here to drop the entire script from the package.

**Comment by paride** [comment]
@toabctl closing this.
