### ISSUE TITLE
growpart: sfdisk is required for resizing dos/MBR partition table. FAILED: failed to get a resizer for format 'dos'

### ISSUE THREAD

**Issue by dandrei** [canonical/cloud-utils#51]
I'm running the following version of `cloud-utils` on an Amazon EC2 instance:

    sudo apt-get install "cloud-guest-utils"
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    cloud-guest-utils is already the newest version (0.32-22-g45fe84a5-0ubuntu1).
    cloud-guest-utils set to manually installed.
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

The `growpart` command fails when attempting to extend the filesystem from 2G to 3G (I used the AWS Console to increase the EBS Volume size):

    sudo growpart /dev/xvda 1
    sfdisk is required for resizing dos/MBR partition table.
    FAILED: failed to get a resizer for format 'dos'

Here are the disk I'm trying to resize:

    sudo lsblk -p
    NAME         MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS
    /dev/xvda    202:0    0   3G  0 disk
    └─/dev/xvda1 202:1    0   2G  0 part /

The filesystem is `ext4`

    sudo lsblk -f
    NAME    FSTYPE FSVER LABEL           UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
    xvda
    └─xvda1 ext4   1.0   cloudimg-rootfs b6adc449-5e3d-4331-ba6b-6e99a75fa48e  278.8M    80% /

What could be the issue?
I followed the guide available here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/recognize-expanded-volume-linux.html

Apparently the partition table is MBR, not GPT, for some reason:

    gdisk -l /dev/xvda
    GPT fdisk (gdisk) version 1.0.8
    
    Partition table scan:
      MBR: MBR only
      BSD: not present
      APM: not present
      GPT: not present
    
    
    ***************************************************************
    Found invalid GPT and valid MBR; converting MBR to GPT format
    in memory.
    ***************************************************************
    
    Disk /dev/xvda: 6291456 sectors, 3.0 GiB
    Sector size (logical/physical): 512/512 bytes
    Disk identifier (GUID): 39CD84BE-22A7-44F3-B8C4-4DC5DC9BDDD0
    Partition table holds up to 128 entries
    Main partition table begins at sector 2 and ends at sector 33
    First usable sector is 34, last usable sector is 6291422
    Partitions will be aligned on 2048-sector boundaries
    Total free space is 2099133 sectors (1025.0 MiB)
    
    Number  Start (sector)    End (sector)  Size       Code  Name
       1            2048         4194303   2.0 GiB     8300  Linux filesystem

**Comment by dandrei** [comment]
Update: the solution was simply installing `fdisk` on the system, and `growpart` knew how to use it.

**Comment by paride** [comment]
We should probably make `fdisk`/`sfdisk` a Recommends in the Debian/Ubuntu packaging.

**Comment by smoser** [comment]
I think it does, no?

https://github.com/canonical/cloud-utils/blob/6e6788e71654474d9c868d6cc942c91bc7ac6cdb/debian/control#L21

and

https://git.launchpad.net/ubuntu/+source/cloud-utils/tree/debian/control#n24

**Comment by paride** [comment]
Right, maybe @dandrei was running a very old version of the package? Anyway I don't think there's a bug here in any recent release of cloud-util (or in git).

**Comment by holmanb** [comment]
> Anyway I don't think there's a bug here in any recent release of cloud-util (or in git).

Agreed, closing
